FROM openjdk:8
RUN apt-get update
RUN apt-get -y install maven
WORKDIR /root
CMD cd /root/KeyValueStore/Chord;mvn clean install -Dmaven.test.skip=true;cd /root/KeyValueStore/ObjectStore;mvn clean compile exec:java
